# Setup
name:         Big Data in the Arts and Humanities
tagline:      Some Arts and Humanities Research Council Projects
baseurl:      ""

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

title: Big Data in the Arts and Humanities
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal